export const SEQUELIZE = 'SEQUELIZE';
export const COURIERS_REPOSITORY = 'COURIERS_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const ORDERS_REPOSITORY = 'ORDERS_REPOSITORY';
export const ADDRESS_REPOSITORY = 'ADDRESS_REPOSITORY';
